### ISSUE TITLE
Getting VBE info block failed (eax=0xc78d2, err=0)

### ISSUE THREAD

**Issue by pete4abw** [mjanusz/v86d#2]
Kernel 5.4.66 got rid of FB scrollback, so I decided to dust off v86d. On this system, at least, it does not load. Relevant error log is shown here. klibc was compiled with the same kernel. It's many years since I've used it and much has changed since 2014. It's probably new hardware and bios are the issue. Thought you would like to know. Cheers.
```
[    0.000000] Command line: BOOT_IMAGE=dev000:\EFI\Slackware\vmlinuz-current  root=/dev/LVM/root2 video=uvesafb:1920x1080-32,mtrr:3,ywrap logo.nologo quiet ro ro                                                                                                
[    0.101003] Kernel command line: BOOT_IMAGE=dev000:\EFI\Slackware\vmlinuz-current  root=/dev/LVM/root2 video=uvesafb:1920x1080-32,mtrr:3,ywrap logo.nologo quiet ro ro
[    0.572290] uvesafb: Getting VBE info block failed (eax=0xc78d2, err=0)
[    0.572292] uvesafb: vbe_init() failed with -22
[    0.572295] uvesafb: probe of uvesafb.0 failed with error -22
```
Kernel 5.4.66
Hardware:
```
*-display                                                                                                                
             description: VGA compatible controller                                                                              
             product: Iris Plus Graphics G7                                                                                      
             vendor: Intel Corporation                                                                                           
             physical id: 2                                                                                                      
             bus info: pci@0000:00:02.0
             version: 07
             width: 64 bits
             clock: 33MHz
             capabilities: vga_controller bus_master cap_list rom
             configuration: driver=i915 latency=0
             resources: irq:140 memory:76000000-76ffffff memory:80000000-8fffffff ioport:7000(size=64) memory:c0000-dffff
```
System
```
    description: Notebook
    product: HP Pavilion Laptop 15-cs3xxx (7RQ09UA#ABA)
    vendor: HP
    version: Type1ProductConfigId
    serial: xxx
    width: 64 bits
    capabilities: smbios-3.2.0 dmi-3.2.0 smp vsyscall32
    configuration: administrator_password=disabled boot=normal chassis=notebook family=103C_5335KV HP Pavilion sku=7RQ09UA#ABA uuid=xxx

  *-core
       description: Motherboard
       product: 86E2
       vendor: HP
       physical id: 0
       version: 95.34
       serial: xxx
       slot: Type2 - Board Chassis Location
     *-firmware
          description: BIOS
          vendor: Insyde
          physical id: 0
          version: F.11
          date: 08/19/2020
          size: 128KiB
          capacity: 12MiB
          capabilities: pci upgrade shadowing cdboot bootselect edd int13floppynec int13floppytoshiba int13floppy360 int13floppy1200 int13floppy720 int13floppy2880 int9keyboard int10video acpi usb biosbootspecification uefi
     *-cpu
          description: CPU
          product: Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
          vendor: Intel Corp.
          physical id: 4
          bus info: cpu@0
          version: Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
          serial: To Be Filled By O.E.M.
          slot: U3E1
          size: 2820MHz
          capacity: 4005MHz
          width: 64 bits
          clock: 100MHz

```

**Comment by proxy-m** [comment]
To avoid the error `uvesafb: Getting VBE info block failed` (-22) you must firstly build-in or load kernel module `vga16fb`, which is used by `uvesafb` in conjunction with helper `/sbin/v86d`.

P.S.: Also if you use initramfs/initrd, maybe you need fix to modules order.
P.P.S.: On later linux versions, developers revert to vesafb support, but some functions of uvesafb may be missed.

**Comment by proxy-m** [comment]
Try https://forums.gentoo.org/viewtopic-t-1096832-start-0.html

and https://forums.gentoo.org/viewtopic-p-8336186.html#8336186

**Comment by pete4abw** [comment]
> To avoid the error `uvesafb: Getting VBE info block failed` (-22) you must firstly build-in or load kernel module `vga16fb`, which is used by `uvesafb` in conjunction with helper `/sbin/v86d`.
> 
> P.S.: Also if you use initramfs/initrd, maybe you need fix to modules order.
> P.P.S.: On later linux versions, developers revert to vesafb support, but some functions of uvesafb may be missed.

Thank you. I will take a look. I may also take a run at 5.4.66 and see what they changed in the Framebuffer code that prevents backscrolling. I realize it may be a security risk, but in X scrolling back on a terminal is standard.

**Comment by proxy-m** [comment]
If `/sbin/v86d` exists, then it just module load order problem. If system already inited and you start uvesafb via modprobe, all works fine.

On the links above you can find solutions to make it work from linux command line too (load order must be correct).

**Comment by pete4abw** [comment]
Thanks @proxy-m . Loading modules showed a similar error but with more detail.
[  149.840277] process '/sbin/v86d' started with executable stack
[  149.840666] v86d: EBDA too big (10800), truncating.
[  149.840703] v86d: c000:7910: 01 ILLEGAL EXTENDED X86 OPCODE!
[  149.840755] uvesafb: Getting VBE info block failed (eax=0xc78d2, err=0)
[  149.840756] uvesafb: vbe_init() failed with -22
[  149.840760] uvesafb: probe of uvesafb.0 failed with error -22

Thanks again. 
PS: The successful examples above all used VESAFB not UVESAFB. Maybe it's something default in my Intel graphics.

**Comment by proxy-m** [comment]
@pete4abw
1) Did you read two links above? They about enabling uvesafb as "built-in" by initrd/initrafm?
2) If you try something like this https://gitlab.com/mikb007/buildroot-dl-mini/-/blob/master/.linux-config_9p linux config , execpt must be CONFIG_FRAMEBUFFER_CONSOLE=y , uvesafb can start with modprobe/insmod.
3) I saw your error `Getting VBE info block failed (eax=0xc78d2, err=0)`, and describe solution.
4) Error `v86d: EBDA too big (10800), truncating.` and ` and `v86d: c000:7910: 01 ILLEGAL EXTENDED X86 OPCODE!` is other error.

Is you kernel same arhitecture as v86d binary (i386 works fine, as I saw)?

Also it may be problem with your vga/vesa bios (video card support vga/vesa protocol, which uvesafb can not understand), but it is strange. Try to make all framebuffers not built-in (especially intel) and start uvesafb with modprobe after system scripts (system v or systemd) finished init.

**Comment by pete4abw** [comment]
I read the links. There was nothing new in them. I've used uvesafb before for years, since 2011. This is newer laptop with built in Intel graphics and nVidia as a second GPU that is unused (no nVidia, nouveau drivers used though, no Optimus). klibc compiled for current kernel, x86_64 only. All Intel modules are configured as [M].

I notice that with no VGA or video= command, my system boots natively in 1920x1080 mode. 

Thanks anyway. Probably a problem with the graphics chipset and the dual GPU.
```
H/W path         Device        Class          Description
=========================================================
/0/100/2                       display        Iris Plus Graphics G7
/0/100/1c.4/0                  display        GP108M [GeForce MX250]
```

I'm closing this issue. I appreciate your help. Cheers.

**Comment by proxy-m** [comment]
> I read the links. There was nothing new in them. I've used uvesafb before for years, since 2011. This is newer laptop with built in Intel graphics and nVidia as a second GPU that is unused (no nVidia, nouveau drivers used though, no Optimus). klibc compiled for current kernel, x86_64 only. All Intel modules are configured as [M].
> 
> I notice that with no VGA or video= command, my system boots natively in 1920x1080 mode.
> 
> Thanks anyway. Probably a problem with the graphics chipset and the dual GPU.
> 
> ```
> H/W path         Device        Class          Description
> =========================================================
> /0/100/2                       display        Iris Plus Graphics G7
> /0/100/1c.4/0                  display        GP108M [GeForce MX250]
> ```
> 
> I'm closing this issue. I appreciate your help. Cheers.

@pete4abw

1. Interesting `Error v86d: EBDA too big (10800), truncating` and `x1080 mode`.

2. Yes, your intel Iris Plus Graphics G7 card (**i915 family**) has buggy vesa/vga bios.
  **To fix it, use 915resolution hook and 915resolution-static:**

<p>
<h2 style="color: rgb(34, 34, 34); background-image: none; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; font-weight: normal; margin: 1em 0px 0.25em; overflow: hidden; padding: 0px; border-bottom: 1px solid rgb(162, 169, 177); font-family: sans-serif; line-height: 1.3;"><span class="mw-headline" id="Uvesafb_and_915resolution">Uvesafb and 915resolution</span></h2>
<p style="margin: 0.5em 0px; line-height: inherit; color: rgb(34, 34, 34); font-family: sans-serif; font-size: 14px;">In the following, we address a more complex scenario. Many intel video chipsets for widescreen laptops are known to have a buggy BIOS, which does not support the main, native resolution of the wide screen! For this reason, 915resolution was created to patch the BIOS at boot time and allow the X server to use the widescreen resolution. Nowadays, the X server is able to do this without the help of 915resolution. However, 915resolution can be combined with uvesafb in order to obtain a widescreen framebuffer, without any need to launch X at all. In this case, we need to load uvesafb after having run 915resolution, so that uvesafb can resort to the proper resolution.</p>
<h3 style="color: rgb(34, 34, 34); background-image: none; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 0.3em 0px 0px; overflow: hidden; padding-top: 0.5em; padding-bottom: 0px; border-bottom: 0px; font-size: 1.2em; line-height: 1.6; font-family: sans-serif;"><span class="mw-headline" id="915resolution-static">915resolution-static</span></h3>
<p style="margin: 0.5em 0px; line-height: inherit; color: rgb(34, 34, 34); font-family: sans-serif; font-size: 14px;">In this scenario, 915resolution needs to be compiled statically (since it is going to be in an initramfs, it can not be linked to external libraries). Thus you CAN NOT use the 915resolution package in the [community] repo. Look instead for&nbsp;<span class="plainlinks archwiki-template-pkg" style="font-family: monospace;"><a rel="nofollow" class="external text" href="https://web.archive.org/web/20140910025647/https://aur.archlinux.org/packages/915resolution-static/" style="text-decoration-line: none; background: green right center no-repeat; padding-right: 13px; font-weight: bold; color: rgb(102, 102, 102) !important; padding-top: 0px !important; padding-bottom: 0px !important; padding-left: 0px !important;">915resolution-static</a></span><sup style="line-height: 1;"><small>AUR</small></sup>: archived in&nbsp;<a rel="nofollow" class="external text" href="https://github.com/felixonmars/aur3-mirror/tree/master/915resolution-static" style="text-decoration-line: none; background: green right center no-repeat; padding-right: 13px; font-weight: bold; color: rgb(102, 102, 102) !important;">aur-mirror</a>]</sup>&nbsp;in the AUR. It compiles 915 resolution statically and provides a 915 resolution hook, so you can run 915resolution before loading uvesafb and get the patched resolution. So install 915resolution-static via makepkg and&nbsp;<a href="https://web.archive.org/web/20190603210338/https://wiki.archlinux.org/index.php/Pacman" title="Pacman" style="text-decoration-line: none; background: none; font-weight: bold; color: rgb(102, 102, 102) !important;">pacman</a>.</p>
<h3 style="color: rgb(34, 34, 34); background-image: none; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 0.3em 0px 0px; overflow: hidden; padding-top: 0.5em; padding-bottom: 0px; border-bottom: 0px; font-size: 1.2em; line-height: 1.6; font-family: sans-serif;"><span class="mw-headline" id="The_resolution">The resolution</span></h3>
<p style="margin: 0.5em 0px; line-height: inherit; color: rgb(34, 34, 34); font-family: sans-serif; font-size: 14px;">You need to edit the 915resolution hook in order to define the BIOS mode you want to replace and and the resolution you want to get. You can get information about all the options for 915resolution with:</p>
<pre style="color: rgb(34, 34, 34); background-color: rgb(235, 241, 245); border: 1px solid rgb(187, 204, 221); padding: 1em; line-height: 1.3em; overflow: auto; word-break: break-all; white-space: pre-wrap !important;">$ 915resolution -h</pre>
<p style="margin: 0.5em 0px; line-height: inherit; color: rgb(34, 34, 34); font-family: sans-serif; font-size: 14px;">Edit&nbsp;<code style="background-color: rgb(235, 241, 245); border: 0px solid rgb(234, 236, 240); border-radius: 0px; padding: 0px 0.3em; display: inline-block;">/lib/initcpio/hooks/915resolution</code>&nbsp;and modify the options for 915resolution:</p>
<pre style="color: rgb(34, 34, 34); background-color: rgb(235, 241, 245); border: 1px solid rgb(187, 204, 221); padding: 1em; line-height: 1.3em; overflow: auto; word-break: break-all; white-space: pre-wrap !important;">run_hook () {<br/>    msg -n &quot;:: Patching the VBIOS...&quot;<br/>    /usr/sbin/915resolution 5c 1280 800<br/>    msg &quot;done.&quot;<br/> }<br/></pre>
<p style="margin: 0.5em 0px; line-height: inherit; color: rgb(34, 34, 34); font-family: sans-serif; font-size: 14px;">As default 5c is the code of the BIOS mode to replace. You can get a list of the available BIOS video modes with the command&nbsp;<code style="background-color: rgb(235, 241, 245); border: 0px solid rgb(234, 236, 240); border-radius: 0px; padding: 0px 0.3em; display: inline-block;">915resolution -l</code>.</p>
<div class="archwiki-template-box archwiki-template-box-note" style="padding: 5px; border: thin solid rgb(187, 187, 221); margin: 0.5em 0px; overflow: hidden; background-color: rgb(221, 221, 255); color: rgb(34, 34, 34); font-family: sans-serif; font-size: 14px;"><strong>Note:</strong>&nbsp;You want to choose the code of a mode that you&nbsp;<em>DO NOT</em>&nbsp;need (neither in the framebuffer nor in X), because 915resolution will replace it with a new user-defined mode. In the above example,&nbsp;<code style="background-color: rgb(235, 241, 245); border: 0px solid rgb(234, 236, 240); border-radius: 0px; padding: 0px 0.3em; display: inline-block;">1280 800</code>&nbsp;is the new desired resolution.</div>
<h3 style="color: rgb(34, 34, 34); background-image: none; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 0.3em 0px 0px; overflow: hidden; padding-top: 0.5em; padding-bottom: 0px; border-bottom: 0px; font-size: 1.2em; line-height: 1.6; font-family: sans-serif;"><span class="mw-headline" id="The_Hooks_Array">The Hooks Array</span></h3>
<p style="margin: 0.5em 0px; line-height: inherit; color: rgb(34, 34, 34); font-family: sans-serif; font-size: 14px;">Add the 915resolution hook and, after it, the v86d hook to HOOKS in&nbsp;<code style="background-color: rgb(235, 241, 245); border: 0px solid rgb(234, 236, 240); border-radius: 0px; padding: 0px 0.3em; display: inline-block;">/etc/mkinitcpio.conf</code>. Put them before the hooks for the keymap, the resume from suspension and the filesystems.</p>
<pre style="color: rgb(34, 34, 34); background-color: rgb(235, 241, 245); border: 1px solid rgb(187, 204, 221); padding: 1em; line-height: 1.3em; overflow: auto; word-break: break-all; white-space: pre-wrap !important;">HOOKS=&quot;base udev 915resolution v86d ...&quot;</pre>
<p style="margin: 0.5em 0px; line-height: inherit; color: rgb(34, 34, 34); font-family: sans-serif; font-size: 14px;">Then you need to regenerate your initramfs with mkinitcpio (adjust the following command to your setup):</p>
<pre style="color: rgb(34, 34, 34); background-color: rgb(235, 241, 245); border: 1px solid rgb(187, 204, 221); padding: 1em; line-height: 1.3em; overflow: auto; word-break: break-all; white-space: pre-wrap !important;">mkinitcpio -p linux</pre>
</p>

Source: https://web.archive.org/web/20190603210338/https://wiki.archlinux.org/index.php/Uvesafb
